# This is a basic workflow to help you get started with Actions

name: CI
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a multi-line script
        run: |
          sudo wget https://yt-dl.org/downloads/latest/youtube-dl -O /usr/local/bin/youtube-dl
          sudo chmod a+rx /usr/local/bin/youtube-dl
          youtube-dl --audio-format mp3 -o live.mp3 https://www.youtube.com/watch?v=WwxBriiftt4
          
