# This is a basic workflow to help you get started with Actions

name: CI
on:
  push:
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: install ffmpeg
        run: |
          for ($var = 1; $var -le 5; $var++) {
          $Rd = Get-Random -Minimum 1 -Maximum 106
          echo $Rd
          if ($Rd -eq 1) {Start-Process chrome.exe '-new-window https://www.youtube.com/watch?v=-Lyr8hOuJyw' }
          if ($Rd -eq 2) {Start-Process chrome.exe '-new-window https://www.youtube.com/watch?v=0axbO1h9v34' }
          if ($Rd -eq 3) {Start-Process chrome.exe '-new-window https://www.youtube.com/watch?v=0gC0Kljb1fc' }
          if ($Rd -eq 4) {Start-Process chrome.exe '-new-window https://www.youtube.com/watch?v=2Z534827nUM' }
          if ($Rd -eq 5) {Start-Process chrome.exe '-new-window https://www.youtube.com/watch?v=2db1JddbUz8' }
          if ($Rd -eq 6) {Start-Process chrome.exe '-new-window https://www.youtube.com/watch?v=3C5JnCf7ev8' }
          if ($Rd -eq 7) {Start-Process chrome.exe '-new-window https://www.youtube.com/watch?v=3KDgOaVgqRo' }
          if ($Rd -eq 8) {Start-Process chrome.exe '-new-window https://www.youtube.com/watch?v=3LgZJNhAgko' }
          if ($Rd -eq 9) {Start-Process chrome.exe '-new-window https://www.youtube.com/watch?v=Hfb41ul8kKQ' }
          if ($Rd -eq 10) {Start-Process chrome.exe '-new-window https://www.youtube.com/watch?v=I-ATaSwZXmc' }
          if ($Rd -eq 11) {Start-Process chrome.exe '-new-window https://www.youtube.com/watch?v=KSNLvGHq-WI' }
          if ($Rd -eq 12) {Start-Process chrome.exe '-new-window https://www.youtube.com/watch?v=L2CX6a0i2aQ' }
          if ($Rd -eq 13) {Start-Process chrome.exe '-new-window https://www.youtube.com/watch?v=MEBwv6GWzxA' }
          if ($Rd -eq 14) {Start-Process chrome.exe '-new-window https://www.youtube.com/watch?v=Nfyqbz_y5Eg' }
          if ($Rd -eq 15) {Start-Process chrome.exe '-new-window https://www.youtube.com/watch?v=OHbLvA6iQRA' }
          if ($Rd -eq 16) {Start-Process chrome.exe '-new-window https://www.youtube.com/watch?v=O_uhpxWpGDs' }
          if ($Rd -eq 17) {Start-Process chrome.exe '-new-window https://www.youtube.com/watch?v=PBQJQYE6jxk' }
          if ($Rd -eq 18) {Start-Process chrome.exe '-new-window https://www.youtube.com/watch?v=PMSsKWQ_2vA' }
          if ($Rd -eq 19) {Start-Process chrome.exe '-new-window https://www.youtube.com/watch?v=PhNSn-H5N6o' }
          if ($Rd -eq 20) {Start-Process chrome.exe '-new-window https://www.youtube.com/watch?v=S_035-4sImI' }
          if ($Rd -eq 21) {Start-Process chrome.exe '-new-window https://www.youtube.com/watch?v=T_6vw_cCkTo' }
          if ($Rd -eq 22) {Start-Process chrome.exe '-new-window https://www.youtube.com/watch?v=VOytceqV67o' }
          if ($Rd -eq 23) {Start-Process chrome.exe '-new-window https://www.youtube.com/watch?v=VPAG9Pe2yNY' }
          if ($Rd -eq 24) {Start-Process chrome.exe '-new-window https://www.youtube.com/watch?v=WC1wQlv_2Us' }
          if ($Rd -eq 25) {Start-Process chrome.exe '-new-window https://www.youtube.com/watch?v=WF_zGyXKbQg' }
          if ($Rd -eq 26) {Start-Process chrome.exe '-new-window https://www.youtube.com/watch?v=WYpvG6GVIZ8' }
          if ($Rd -eq 27) {Start-Process chrome.exe '-new-window https://www.youtube.com/watch?v=YjZb1k9v0kI' }
          if ($Rd -eq 28) {Start-Process chrome.exe '-new-window https://www.youtube.com/watch?v=cPpKdVTYO10' }
          if ($Rd -eq 29) {Start-Process chrome.exe '-new-window https://www.youtube.com/watch?v=ZYoynRzUP1s' }
          if ($Rd -eq 30) {Start-Process chrome.exe '-new-window https://www.youtube.com/watch?v=iUcttvSdjPw' }
          if ($Rd -eq 31) {Start-Process chrome.exe '-new-window https://www.youtube.com/watch?v=k3S-AYfC6c0' }
          if ($Rd -eq 32) {Start-Process chrome.exe '-new-window https://www.youtube.com/watch?v=kr8raK-nxkM' }
          if ($Rd -eq 33) {Start-Process chrome.exe '-new-window https://www.youtube.com/watch?v=oQIPI2QcgiY' }
          if ($Rd -eq 34) {Start-Process chrome.exe '-new-window https://www.youtube.com/watch?v=orSE0I8NE9k' }
          if ($Rd -eq 35) {Start-Process chrome.exe '-new-window https://www.youtube.com/watch?v=pZA9JIvXnrk' }
          if ($Rd -eq 36) {Start-Process chrome.exe '-new-window https://www.youtube.com/watch?v=pZGZMWpQ0Q4' }
          if ($Rd -eq 37) {Start-Process chrome.exe '-new-window https://www.youtube.com/watch?v=qnnZQJgU-t4' }
          if ($Rd -eq 38) {Start-Process chrome.exe '-new-window https://www.youtube.com/watch?v=rTOKHDAI6uw' }
          if ($Rd -eq 39) {Start-Process chrome.exe '-new-window https://www.youtube.com/watch?v=seMLHI-OlLk' }
          if ($Rd -eq 40) {Start-Process chrome.exe '-new-window https://www.youtube.com/watch?v=sgRm6Qa79Wc' }
          if ($Rd -eq 41) {Start-Process chrome.exe '-new-window https://www.youtube.com/watch?v=tgk0lkv6ygU' }
          if ($Rd -eq 42) {Start-Process chrome.exe '-new-window https://www.youtube.com/watch?v=u2bgZ08klfo' }
          if ($Rd -eq 43) {Start-Process chrome.exe '-new-window https://www.youtube.com/watch?v=v9DwqaX7W0U' }
          if ($Rd -eq 44) {Start-Process chrome.exe '-new-window https://www.youtube.com/watch?v=uITEnsM2LmE' }
          if ($Rd -eq 45) {Start-Process chrome.exe '-new-window https://www.youtube.com/watch?v=x3TbIwoNr30' }
          if ($Rd -eq 46) {Start-Process chrome.exe '-new-window https://www.youtube.com/watch?v=vsJjIV1CNoQ' }
          if ($Rd -eq 47) {Start-Process chrome.exe '-new-window https://www.youtube.com/watch?v=H-93aR5hsxg' }
          if ($Rd -eq 48) {Start-Process chrome.exe '-new-window https://www.youtube.com/watch?v=SjysDDtCjCM' }
          if ($Rd -eq 49) {Start-Process chrome.exe '-new-window https://www.youtube.com/watch?v=sVE3wzKyYxg' }
          if ($Rd -eq 50) {Start-Process chrome.exe '-new-window https://www.youtube.com/watch?v=pR5co363qLc' }
          if ($Rd -eq 51) {Start-Process chrome.exe '-new-window https://www.youtube.com/watch?v=aHjoZ6nJrQY' }
          if ($Rd -eq 52) {Start-Process chrome.exe '-new-window https://www.youtube.com/watch?v=LL2V6JxGJSs' }
          if ($Rd -eq 53) {Start-Process chrome.exe '-new-window https://www.youtube.com/watch?v=GiSEDRjr7HQ' }
          if ($Rd -eq 54) {Start-Process chrome.exe '-new-window https://www.youtube.com/watch?v=Znh74_Q1HjA' }
          if ($Rd -eq 55) {Start-Process chrome.exe '-new-window https://www.youtube.com/watch?v=jVT9h9v7WfA' }
          if ($Rd -eq 56) {Start-Process chrome.exe '-new-window https://www.youtube.com/watch?v=kj5mfdWb-Zw' }
          if ($Rd -eq 57) {Start-Process chrome.exe '-new-window https://www.youtube.com/watch?v=S6mgi9inWek' }
          if ($Rd -eq 58) {Start-Process chrome.exe '-new-window https://www.youtube.com/watch?v=r35PJ5OO9sM' }
          if ($Rd -eq 59) {Start-Process chrome.exe '-new-window https://www.youtube.com/watch?v=suJZyZeVpfk' }
          if ($Rd -eq 60) {Start-Process chrome.exe '-new-window https://www.youtube.com/watch?v=PKj2pOrsCj8' }
          if ($Rd -eq 61) {Start-Process chrome.exe '-new-window https://www.youtube.com/watch?v=9yixxCYOmF8' }
          if ($Rd -eq 62) {Start-Process chrome.exe '-new-window https://www.youtube.com/watch?v=onkZbsKTnXU' }
          if ($Rd -eq 63) {Start-Process chrome.exe '-new-window https://www.youtube.com/watch?v=r2TbdtoaL7A' }
          if ($Rd -eq 64) {Start-Process chrome.exe '-new-window https://www.youtube.com/watch?v=A0xlt9Wcoaw' }
          if ($Rd -eq 65) {Start-Process chrome.exe '-new-window https://www.youtube.com/watch?v=NcvT2Z8Ap1o' }
          if ($Rd -eq 66) {Start-Process chrome.exe '-new-window https://www.youtube.com/watch?v=OkA04seO3_4' }
          if ($Rd -eq 67) {Start-Process chrome.exe '-new-window https://www.youtube.com/watch?v=SUy0kZ4TG0g' }
          if ($Rd -eq 68) {Start-Process chrome.exe '-new-window https://www.youtube.com/watch?v=biNhdt3f7nQ' }
          if ($Rd -eq 69) {Start-Process chrome.exe '-new-window https://www.youtube.com/watch?v=nLoNxh6J_WU' }
          if ($Rd -eq 70) {Start-Process chrome.exe '-new-window https://www.youtube.com/watch?v=o4rsl-024aA' }
          if ($Rd -eq 71) {Start-Process chrome.exe '-new-window https://www.youtube.com/watch?v=piMP8dgcurs' }
          if ($Rd -eq 72) {Start-Process chrome.exe '-new-window https://www.youtube.com/watch?v=pkOsSZT-xwQ' }
          if ($Rd -eq 73) {Start-Process chrome.exe '-new-window https://www.youtube.com/watch?v=x--aH3Ask9g' }
          if ($Rd -eq 74) {Start-Process chrome.exe '-new-window https://www.youtube.com/watch?v=xzlgBgXO85w' }
          if ($Rd -eq 75) {Start-Process chrome.exe '-new-window https://www.youtube.com/watch?v=SGKquJzH_0s' }
          if ($Rd -eq 76) {Start-Process chrome.exe '-new-window https://www.youtube.com/watch?v=jp8T2QRunL4' }
          if ($Rd -eq 77) {Start-Process chrome.exe '-new-window https://www.youtube.com/watch?v=qbtsVHuk5bE' }
          if ($Rd -eq 78) {Start-Process chrome.exe '-new-window https://www.youtube.com/watch?v=AR-QUjX5uCg' }
          if ($Rd -eq 79) {Start-Process chrome.exe '-new-window https://www.youtube.com/watch?v=B60ZzTESR6c' }
          if ($Rd -eq 80) {Start-Process chrome.exe '-new-window https://www.youtube.com/watch?v=Kpzy8sU3ycs' }
          if ($Rd -eq 81) {Start-Process chrome.exe '-new-window https://www.youtube.com/watch?v=MMesc6dtPFI' }
          if ($Rd -eq 82) {Start-Process chrome.exe '-new-window https://www.youtube.com/watch?v=2DNKZSuJ03E' }
          if ($Rd -eq 83) {Start-Process chrome.exe '-new-window https://www.youtube.com/watch?v=5GhOaI1fbfQ' }
          if ($Rd -eq 84) {Start-Process chrome.exe '-new-window https://www.youtube.com/watch?v=7PG7wc3peSw' }
          if ($Rd -eq 85) {Start-Process chrome.exe '-new-window https://www.youtube.com/watch?v=7m7GLFioZLQ' }
          if ($Rd -eq 86) {Start-Process chrome.exe '-new-window https://www.youtube.com/watch?v=8lAMyJ8sOUk' }
          if ($Rd -eq 87) {Start-Process chrome.exe '-new-window https://www.youtube.com/watch?v=EpEl0GismKw' }
          if ($Rd -eq 88) {Start-Process chrome.exe '-new-window https://www.youtube.com/watch?v=LqZl6qZqLJ4' }
          if ($Rd -eq 89) {Start-Process chrome.exe '-new-window https://www.youtube.com/watch?v=N0ostYZKmpk' }
          if ($Rd -eq 90) {Start-Process chrome.exe '-new-window https://www.youtube.com/watch?v=SMdAci0DZeA' }
          if ($Rd -eq 91) {Start-Process chrome.exe '-new-window https://www.youtube.com/watch?v=_f4M7tQRAAI' }
          if ($Rd -eq 92) {Start-Process chrome.exe '-new-window https://www.youtube.com/watch?v=_f4M7tQRAAI' }
          if ($Rd -eq 93) {Start-Process chrome.exe '-new-window https://www.youtube.com/watch?v=acgA3O1MzNA' }
          if ($Rd -eq 94) {Start-Process chrome.exe '-new-window https://www.youtube.com/watch?v=d_f6clz5hZE' }
          if ($Rd -eq 95) {Start-Process chrome.exe '-new-window https://www.youtube.com/watch?v=b9u_osS9CDc' }
          if ($Rd -eq 96) {Start-Process chrome.exe '-new-window https://www.youtube.com/watch?v=fg2oPeNOYkw' }
          if ($Rd -eq 97) {Start-Process chrome.exe '-new-window https://www.youtube.com/watch?v=jvQ-TgaXrrY' }
          if ($Rd -eq 98) {Start-Process chrome.exe '-new-window https://www.youtube.com/watch?v=m41cvbQSEg0' }
          if ($Rd -eq 99) {Start-Process chrome.exe '-new-window https://www.youtube.com/watch?v=n35p448PxF4' }
          if ($Rd -eq 100) {Start-Process chrome.exe '-new-window https://www.youtube.com/watch?v=osnDOL34gjI' }
          if ($Rd -eq 101) {Start-Process chrome.exe '-new-window https://www.youtube.com/watch?v=pD_qOQWAKjQ' }
          if ($Rd -eq 102) {Start-Process chrome.exe '-new-window https://www.youtube.com/watch?v=qV2QjliCPi0' }
          if ($Rd -eq 103) {Start-Process chrome.exe '-new-window https://www.youtube.com/watch?v=qhodFqiJwd8' }
          if ($Rd -eq 104) {Start-Process chrome.exe '-new-window https://www.youtube.com/watch?v=rKfYuXcKx9c' }
          if ($Rd -eq 105) {Start-Process chrome.exe '-new-window https://www.youtube.com/watch?v=uB_en5g0DCg' }

          }
          Start-Sleep 1800
