# This is a basic workflow to help you get started with Actions

name: CI
on:
  push:
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: install ffmpeg
        run: |
          Start-Process firefox.exe '-new-window https://www.youtube.com/watch?v=-Lyr8hOuJyw'
