name: nonton
on:
  push:
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: chrome.exe
        run: |
          Start-Process chrome.exe '-new-window https://www.youtube.com/watch?v=-Lyr8hOuJyw'
          Start-Process msedge.exe '-new-window https://www.youtube.com/watch?v=-Lyr8hOuJyw'
          start-sleep 103
          Add-Type -AssemblyName System.Windows.Forms,System.Drawing
          $screens = [Windows.Forms.Screen]::AllScreens
          $top    = ($screens.Bounds.Top    | Measure-Object -Minimum).Minimum
          $left   = ($screens.Bounds.Left   | Measure-Object -Minimum).Minimum
          $width  = ($screens.Bounds.Right  | Measure-Object -Maximum).Maximum
          $height = ($screens.Bounds.Bottom | Measure-Object -Maximum).Maximum
          $bounds   = [Drawing.Rectangle]::FromLTRB($left, $top, $width, $height)
          $bmp      = New-Object System.Drawing.Bitmap ([int]$bounds.width), ([int]$bounds.height)
          $graphics = [Drawing.Graphics]::FromImage($bmp)
          $graphics.CopyFromScreen($bounds.Location, [Drawing.Point]::Empty, $bounds.size)
          $bmp.Save(".\test.png")
          $graphics.Dispose()
          $bmp.Dispose()
          git add test.png
          git config --global user.name 'Your Name'
          git config --global user.email 'your-username@users.noreply.github.com'
          git commit -am "Automated report"
          git push
