# This is a basic workflow to help you get started with Actions

name: CI
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a multi-line script
        run: |
          sudo apt-get install ffmpeg -y
          wget https://github.com/mooghen1/manga-list/releases/download/v1.1.1/tets1.rar
          ls
          
