# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Run a one-line script
        run: | 
          start chrome https://youtube.com/live/kj5mfdWb-Zw?feature=share
          Start-Sleep 2555
