# This is a basic workflow to help you get started with Actions

name: CI
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: install ffmpeg
        run: |
          
          1="https://www.youtube.com/watch?v=-Lyr8hOuJyw"
          echo $1
          docker run -d \
              --name=firefox \
              -p 5800:5800 \
              -e FF_OPEN_URL= $1
              -v /docker/appdata/firefox:/config:rw \
              jlesage/firefox
          
