# This is a basic workflow to help you get started with Actions

name: CI
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a multi-line script
        run: |
          while :
          do
            rm te.txt
            wget https://raw.githubusercontent.com/mooghen1/vvvv/main/te.txt
            AAA=`cat te.txt`
              if [ $AAA -eq 0 ]
              then
                echo 0
                break
              else
                echo 1
              fi
          done
          echo clear
          #git add te.txt
          #git config --global user.name 'Your Name'
          #git config --global user.email 'your-username@users.noreply.github.com'
          #git commit -am "Automated report"
          #git push
