name: CI
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          google-chrome https://www.youtube.com/watch?v=fKlrKDuLjBk&list=PLo7Xh7fZc_kUgUEIh5EpPcfZvSU8H2M-T&index=62
        
