# This is a basic workflow to help you get started with Actions

name: CI
on:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: AnimMouse/setup-yt-dlp@v1
        #with:
        #  with-ffmpeg: true
      - name: Run a multi-line script
        run: yt-dlp --downloader aria2c -P cvideo  https://www.youtube.com/watch?v=B7QzbCViK0E
      - run: sudo apt install -y ffmpeg
      - name: Run a multi-line script
        run: mv cvideo/*.mp4 cvideo.mp4
      - run: |
          ffmpeg -i cvideo.mp4 -vn audio.mp3
          ls
