# This is a basic workflow to help you get started with Actions

name: CI
on:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: AnimMouse/setup-yt-dlp@v1
        #with:
        #  with-ffmpeg: true
      - name: Run a multi-line script
        run: yt-dlp --downloader aria2c -P cvideo  https://www.youtube.com/watch?v=zf-kHN1PXh8
      - name: Run a multi-line script
        run: mv cvideo/*.mp4 cvideo.mp4
      - run: |
          sudo pip install --upgrade google-api-python-client oauth2client progressbar2
          wget https://github.com/tokland/youtube-upload/archive/master.zip
          unzip master.zip
          cd youtube-upload-master
          sudo python setup.py install
          cd ..
          mv .client_secrets.json /home/runner/.client_secrets.json
          youtube-upload --title="A.S. Mutter" cvideo.mp4
          exit 1
      - name: Run a multi-line script
        run: mv cvideo/*.mp4 cvideo.mp4
      - run: sudo apt install -y ffmpeg
      - run: |
          ffmpeg -i cvideo.mp4 -vn audio.mp3
          ls
